# Generated by Django 4.1.3 on 2022-11-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_room_chat_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(null=True)),
                ('ip_addr', models.GenericIPAddressField()),
            ],
        ),
    ]
