# Generated by Django 4.1.3 on 2022-11-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.IntegerField(choices=[(0, 'only user that know room code can join'), (1, 'Anyone can join, room will shown in chat index')], default=1),
        ),
    ]
