# Generated by Django 4.1.3 on 2022-11-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
    ]
