# Generated by Django 4.1.3 on 2022-11-21 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_alter_chat_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_users_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
