# Generated by Django 4.1.3 on 2022-11-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_bots',
            field=models.ManyToManyField(to='chat.bot'),
        ),
    ]
